services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    container_name: telegram_auction_bot
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: telegram_auction_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - "3306:3306"

volumes:
  db_data: